export const APP_UPDATE_REQUIRED = 'APP_UPDATE_REQUIRED';

export const POST_FACEBOOK_SIGNUP_SUCCESS = 'POST_FACEBOOK_SIGNUP_SUCCESS';
export const POST_FACEBOOK_LOGIN_SUCCESS = 'POST_FACEBOOK_LOGIN_SUCCESS';
export const POST_FACEBOOK_SIGNUP_FAILURE = 'POST_FACEBOOK_SIGNUP_FAILURE';

export const PUT_USER_INFO_SUCCESS = 'PUT_USER_INFO_SUCCESS';
export const PUT_USER_INFO_FAILURE = 'PUT_USER_INFO_FAILURE';

export const PUT_USER_INFO_PREFERRED_TAGS_SUCCESS = 'PUT_USER_INFO_PREFERRED_TAGS_SUCCESS';
export const PUT_USER_INFO_PREFERRED_TAGS_FAILURE = 'PUT_USER_INFO_PREFERRED_TAGS_FAILURE';

export const FETCH_REVIEW_MAIN_FIRST_SUCCESS = 'FETCH_REVIEW_MAIN_FIRST_SUCCESS';
export const FETCH_REVIEW_MAIN_CONTINUE_SUCCESS = 'FETCH_REVIEW_MAIN_CONTINUE_SUCCESS';
export const FETCH_REVIEW_MAIN_LAST_SUCCESS = 'FETCH_REVIEW_MAIN_LAST_SUCCESS';
export const FETCH_REVIEW_MAIN_FAILURE = 'FETCH_REVIEW_MAIN_FAILURE';

export const POST_REVIEW_LIKE_SUCCESS = 'POST_REVIEW_LIKE_SUCCESS';
export const POST_REVIEW_LIKE_DUPLICATION = 'POST_REVIEW_LIKE_DUPLICATION';
export const POST_REVIEW_LIKE_FAILURE = 'POST_REVIEW_LIKE_FAILURE';

export const SELECT_REVIEW_FILTER_SUCCESS = 'SELECT_REVIEW_FILTER_SUCCESS';
export const SELECT_REVIEW_FILTER_FAILURE = 'SELECT_REVIEW_FILTER_FAILURE';

export const SELECT_WEBTOON_RANKING_FILTER_SUCCESS = 'SELECT_WEBTOON_RANKING_FILTER_SUCCESS';
export const SELECT_WEBTOON_RANKING_FILTER_FAILURE = 'SELECT_WEBTOON_RANKING_FILTER_FAILURE';

export const FETCH_WEBTOON_INFO_SUCCESS = 'FETCH_WEBTOON_INFO_SUCCESS';
export const FETCH_WEBTOON_INFO_FAILURE = 'FETCH_WEBTOON_INFO_FAILURE';

export const FETCH_REVIEW_DETAIL_FIRST_SUCCESS = 'FETCH_REVIEW_DETAIL_FIRST_SUCCESS';
export const FETCH_REVIEW_DETAIL_CONTINUE_SUCCESS = 'FETCH_REVIEW_DETAIL_CONTINUE_SUCCESS';
export const FETCH_REVIEW_DETAIL_LAST_SUCCESS = 'FETCH_REVIEW_DETAIL_LAST_SUCCESS';
export const FETCH_REVIEW_DETAIL_FAILURE = 'FETCH_REVIEW_DETAIL_FAILURE';

export const POST_BOOKMARK_SAVE_SUCCESS = 'POST_BOOKMARK_SAVE_SUCCESS';
export const POST_BOOKMARK_DELETE_SUCCESS = 'POST_BOOKMARK_DELETE_SUCCESS';
export const POST_BOOKMARK_FAILURE = 'POST_BOOKMARK_FAILURE';

export const FETCH_BOOKMARK_FIRST_SUCCESS = 'FETCH_BOOKMARK_SUCCESS';
export const FETCH_BOOKMARK_CONTINUE_SUCCESS = 'FETCH_BOOKMARK_CONTINUE_SUCCESS';
export const FETCH_BOOKMARK_LAST_SUCCESS = 'FETCH_BOOKMARK_LAST_SUCCESS';
export const FETCH_BOOKMARK_FAILURE = 'FETCH_BOOKMARK_FAILURE';

export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK_FAILURE = 'DELETE_BOOKMARK_FAILURE';

export const FETCH_SEARCH_WEBTOON_FIRST_SUCCESS = 'FETCH_SEARCH_WEBTOON_FIRST_SUCCESS';
export const FETCH_SEARCH_WEBTOON_CONTINUE_SUCCESS = 'FETCH_SEARCH_WEBTOON_CONTINUE_SUCCESS';
export const FETCH_SEARCH_WEBTOON_LAST_SUCCESS = 'FETCH_SEARCH_WEBTOON_LAST_SUCCESS';
export const FETCH_SEARCH_WEBTOON_FAILURE = 'FETCH_SEARCH_WEBTOON_FAILURE';

export const FETCH_WRITE_SEARCH_WEBTOON_FIRST_SUCCESS = 'FETCH_WRITE_SEARCH_WEBTOON_FIRST_SUCCESS';
export const FETCH_WRITE_SEARCH_WEBTOON_CONTINUE_SUCCESS = 'FETCH_WRITE_SEARCH_WEBTOON_CONTINUE_SUCCESS';
export const FETCH_WRITE_SEARCH_WEBTOON_LAST_SUCCESS = 'FETCH_WRITE_SEARCH_WEBTOON_LAST_SUCCESS';
export const FETCH_WRITE_SEARCH_WEBTOON_FAILURE = 'FETCH_WRITE_SEARCH_WEBTOON_FAILURE';

export const SELECT_WEBTOON_SUCCESS = 'SELECT_WEBTOON_SUCCESS';
export const SELECT_WEBTOON_FAILURE = 'SELECT_WEBTOON_FAILURE';

export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_UPDATE = 'POST_REVIEW_UPDATE';
export const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';
export const ADD_REVIEW_COUNT = 'ADD_REVIEW_COUNT';

export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';

export const FETCH_FILTER_TAG_SUCCESS = 'FETCH_FILTER_TAG_SUCCESS';
export const FETCH_FILTER_TAG_FAILURE = 'FETCH_FILTER_TAG_FAILURE';

export const FETCH_SEARCH_TAG_SUCCESS = 'FETCH_SEARCH_TAG_SUCCESS';
export const FETCH_SEARCH_TAG_FAILURE = 'FETCH_SEARCH_TAG_FAILURE';

export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

export const FETCH_MY_REVIEW_FIRST_SUCCESS = 'FETCH_MY_REVIEW_FIRST_SUCCESS';
export const FETCH_MY_REVIEW_CONTINUE_SUCCESS = 'FETCH_MY_REVIEW_CONTINUE_SUCCESS';
export const FETCH_MY_REVIEW_LAST_SUCCESS = 'FETCH_MY_REVIEW_LAST_SUCCESS';
export const FETCH_MY_REVIEW_FAILURE = 'FETCH_MY_REVIEW_FAILURE';

export const PUT_USER_PUSH_TYPE_SUCCESS = 'PUT_USER_PUSH_TYPE_SUCCESS';
export const PUT_USER_PUSH_TYPE_FAILURE = 'PUT_USER_PUSH_TYPE_FAILURE';

export const FETCH_NOTICE_LIST_SUCCESS = 'FETCH_NOTICE_LIST_SUCCESS';
export const FETCH_NOTICE_LIST_FAILURE = 'FETCH_NOTICE_LIST_FAILURE';

export const FETCH_NOTICE_DETAIL_SUCCESS = 'FETCH_NOTICE_DETAIL_SUCCESS';
export const FETCH_NOTICE_DETAIL_FAILURE = 'FETCH_NOTICE_DETAIL_FAILURE';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const FETCH_RANKING_FIRST_SUCCESS = 'FETCH_RANKING_FIRST_SUCCESS';
export const FETCH_RANKING_CONTINUE_SUCCESS = 'FETCH_RANKING_CONTINUE_SUCCESS';
export const FETCH_RANKING_LAST_SUCCESS = 'FETCH_RANKING_LAST_SUCCESS';
export const FETCH_RANKING_FAILURE = 'FETCH_RANKING_FAILURE';

export const READ_MORE_SUCCESS = 'READ_MORE_SUCCESS';
export const READ_MORE_FAILURE = 'READ_MORE_FAILURE';

export const FETCH_WEBTOON_RANKING_FIRST_SUCCESS = 'FETCH_WEBTOON_RANKING_FIRST_SUCCESS';
export const FETCH_WEBTOON_RANKING_CONTINUE_SUCCESS = 'FETCH_WEBTOON_RANKING_CONTINUE_SUCCESS';
export const FETCH_WEBTOON_RANKING_LAST_SUCCESS = 'FETCH_WEBTOON_RANKING_LAST_SUCCESS';
export const FETCH_WEBTOON_RANKING_FAILURE = 'FETCH_WEBTOON_RANKING_FAILURE';

export const FETCH_TOP_WEBTOON_SUCCESS = 'FETCH_TOP_WEBTOON_SUCCESS';
export const FETCH_TOP_WEBTOON_FAILURE = 'FETCH_TOP_WEBTOON_FAILURE';