export const FETCH_ISSUES_SUCCESS = "FETCH_ISSUES_SUCCESS";
export const FETCH_ISSUES_FAILURE = "FETCH_ISSUES_FAILURE";

export const FETCH_ISSUE_DETAIL_SUCCESS = "FETCH_ISSUE_DETAIL_SUCCESS";
export const FETCH_ISSUE_DETAIL_FAILURE = "FETCH_ISSUE_DETAIL_FAILURE";

export const SELECT_ISSUE_FILTER_SUCCESS = "SELECT_ISSUE_FILTER_SUCCESS";
export const SELECT_ISSUE_FILTER_FAILURE = "SELECT_ISSUE_FILTER_FAILURE";

export const FETCH_COMMENTS_FIRST_SUCCESS = "FETCH_COMMENTS_FIRST_SUCCESS";
export const FETCH_COMMENTS_CONTINUE_SUCCESS =
  "FETCH_COMMENTS_CONTINUE_SUCCESS";
export const FETCH_COMMENTS_LAST_SUCCESS = "FETCH_COMMENTS_LAST_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
