export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';

export const FETCH_ISSUE_DETAIL_SUCCESS = 'FETCH_ISSUE_DETAIL_SUCCESS';
export const FETCH_ISSUE_DETAIL_FAILURE = 'FETCH_ISSUE_DETAIL_FAILURE';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';